# Generated by Django 4.2 on 2023-04-29 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollegeModel',
        ),
    ]
