# Generated by Django 4.2.1 on 2023-05-07 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegemodel',
            name='coordinator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='college_coordinator', to='authentication.usermodel'),
            preserve_default=False,
        ),
    ]
