# Generated by Django 4.2 on 2023-04-26 15:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('category_name', models.CharField(max_length=50)),
                ('category_img', models.ImageField(upload_to='category')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='event_category', to='app.categorymodel'),
            preserve_default=False,
        ),
    ]
