# Generated by Django 4.2 on 2023-04-29 13:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_delete_collegemodel'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('college_name', models.CharField(max_length=50, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='college')),
                ('points', models.IntegerField(default=0)),
                ('gs_name', models.CharField(max_length=50)),
                ('gs_number', models.CharField(max_length=14)),
                ('cs_name', models.CharField(max_length=50)),
                ('cs_number', models.CharField(max_length=14)),
                ('is_paid', models.BooleanField(default=False)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_signature', models.CharField(blank=True, max_length=100, null=True)),
                ('coordinator', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_coordinator', to='authentication.usermodel')),
            ],
            options={
                'db_table': 'college',
            },
        ),
    ]
