# Generated by Django 4.2 on 2023-04-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_collegemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegemodel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
