# Generated by Django 4.2 on 2023-04-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_collegemodel_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='timing',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='venue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
